import { createRequestHandler } from "react-router";

// Generated by `react-router build`.
// @ts-expect-error The server build does not exist before the build step.
import * as build from "./build/server/index.js";

type Env = {
  ASSETS: {
    fetch(request: Request): Promise<Response>;
  };
  LAMBDA_API_ORIGIN: string;
  INTERNAL_PROXY_TOKEN?: string;
};

type ExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};

const ssrHandler = createRequestHandler(build, import.meta.env?.MODE);

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const url = new URL(request.url);

    if (url.pathname.startsWith("/api/")) {
      return proxyToLambda(request, env);
    }

    const assetResponse = await env.ASSETS.fetch(request);
    if (assetResponse.status !== 404) {
      return assetResponse;
    }

    ctx.passThroughOnException();
    return ssrHandler(request);
  },
};

function proxyToLambda(request: Request, env: Env) {
  const incomingUrl = new URL(request.url);
  const upstreamUrl = new URL(incomingUrl.pathname + incomingUrl.search, env.LAMBDA_API_ORIGIN);
  const headers = new Headers(request.headers);

  headers.delete("host");
  if (env.INTERNAL_PROXY_TOKEN) {
    headers.set("X-Internal-Proxy-Token", env.INTERNAL_PROXY_TOKEN);
  }

  return fetch(upstreamUrl, {
    method: request.method,
    headers,
    body: request.method === "GET" || request.method === "HEAD" ? undefined : request.body,
    redirect: "manual",
  });
}
