import { createRequestHandler } from "react-router";

// Generated by `react-router build`.
// @ts-expect-error The server build does not exist before the build step.
import * as build from "./build/server/index.js";

type Env = {
  ASSETS: {
    fetch(request: Request): Promise<Response>;
  };
  LAMBDA_API_ORIGIN: string;
  INTERNAL_PROXY_TOKEN?: string;
  PREVIEW_ID?: string;
};

type ExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};

const ssrHandler = createRequestHandler(build, import.meta.env?.MODE);

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const url = new URL(request.url);

    if (url.pathname.startsWith("/api/")) {
      console.log("api proxy request", {
        method: request.method,
        path: url.pathname,
      });

      return proxyToLambda(request, env);
    }

    const assetResponse = await env.ASSETS.fetch(request);
    if (assetResponse.status !== 404) {
      return assetResponse;
    }

    ctx.passThroughOnException();
    return ssrHandler(request);
  },
};

async function proxyToLambda(request: Request, env: Env) {
  const incomingUrl = new URL(request.url);
  const upstreamUrl = new URL(incomingUrl.pathname + incomingUrl.search, env.LAMBDA_API_ORIGIN);
  const headers = new Headers(request.headers);
  const startedAt = Date.now();

  console.log("proxy to lambda", {
    method: request.method,
    path: incomingUrl.pathname,
    upstreamOrigin: upstreamUrl.origin,
  });

  headers.delete("host");
  if (env.INTERNAL_PROXY_TOKEN) {
    headers.set("X-Internal-Proxy-Token", env.INTERNAL_PROXY_TOKEN);
  }
  if (env.PREVIEW_ID) {
    headers.set("X-Preview-Id", env.PREVIEW_ID);
  }

  let response: Response;
  try {
    response = await fetch(upstreamUrl, {
      method: request.method,
      headers,
      body: request.method === "GET" || request.method === "HEAD" ? undefined : request.body,
      redirect: "manual",
    });
  } catch (error) {
    console.error("lambda proxy fetch failed", {
      method: request.method,
      path: incomingUrl.pathname,
      upstreamOrigin: upstreamUrl.origin,
      cause: error instanceof Error ? error.name : "UnknownError",
      message: error instanceof Error ? error.message : undefined,
      durationMs: Date.now() - startedAt,
    });

    return Response.json(
      { code: "lambda_proxy_fetch_failed", error: "Lambda proxy request failed." },
      {
        status: 502,
        headers: {
          "X-Token-Query-Proxy": "cloudflare-worker",
        },
      },
    );
  }

  console.log("lambda proxy response", {
    method: request.method,
    path: incomingUrl.pathname,
    status: response.status,
    durationMs: Date.now() - startedAt,
  });

  if (response.status >= 500) {
    const bodySnippet = await response
      .clone()
      .text()
      .then((body) => body.slice(0, 500))
      .catch(() => "<unavailable>");

    console.error("lambda proxy upstream error", {
      method: request.method,
      path: incomingUrl.pathname,
      status: response.status,
      contentType: response.headers.get("content-type"),
      bodySnippet,
    });
  }

  const proxiedHeaders = new Headers(response.headers);
  const proxiedResponse = new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers: proxiedHeaders,
  });
  proxiedResponse.headers.set("X-Token-Query-Proxy", "cloudflare-worker");
  proxiedResponse.headers.set("X-Token-Query-Upstream-Status", String(response.status));
  return proxiedResponse;
}
